### ISSUE TITLE
通读完源码后有几个疑问希望得到解答

### ISSUE THREAD

**Issue by a775189488** [wj596/go-mysql-transfer#25]
1. 目前多节点部署只是起到了主备的作用？因为备节点是不打开canal的所以可以理解为不工作吗？
2. 目前对于每一个onRow过来的数据处理都是串行处理，在mysql并发增删改查数量特别大时处理速度是否会存在瓶颈？
3. 能否提供一个改动方案在同步mysql数据时添加一定量的业务逻辑处理。比如同步某个表数据时需要做一些逻辑运算。

Thank！

**Comment by wj596** [comment]
1、是的，高可用集群，主从模式；
2、是串行处理，顺序是为保证数据的一致性，和binglong一致。比如数据库操作的事件是先添加后删除，如果并发不能保证这个顺序，同步到接收端数据就不对；
增量实时同步需要和数据库的增删改操作保持一致，数据库的每一个操作都会映射到接收端；
全量数据初始化的时候就是并发的，因为不需要保证顺序；
处理速度与网络和接收端有关，文档上面有性能测试说明可供参考；
MySQL主从复制本来就有一定的延迟，通常都是毫秒计，但是并发量超大会延迟增大；如果项目的并发量特大，对响应时间要求苛刻，建议让同步工具监听一个从节点；
3、业务逻辑处理可以通过Lua脚本扩展实现，这样可不用改动代码；如果有能力改源码，也可以定制，在endpoint->Consume方法中处理也可以

**Comment by a775189488** [comment]
> 1、是的，高可用集群，主从模式；
> 2、是串行处理，顺序是为保证数据的一致性，和binglong一致。比如数据库操作的事件是先添加后删除，如果并发不能保证这个顺序，同步到接收端数据就不对；
> 增量实时同步需要和数据库的增删改操作保持一致，数据库的每一个操作都会映射到接收端；
> 全量数据初始化的时候就是并发的，因为不需要保证顺序；
> 处理速度与网络和接收端有关，文档上面有性能测试说明可供参考；
> MySQL主从复制本来就有一定的延迟，通常都是毫秒计，但是并发量超大会延迟增大；如果项目的并发量特大，对响应时间要求苛刻，建议让同步工具监听一个从节点；
> 3、业务逻辑处理可以通过Lua脚本扩展实现，这样可不用改动代码；如果有能力改源码，也可以定制，在endpoint->Consume方法中处理也可以

好的，感谢回复，今天又深入看了下代码，发现一个小问题：
- 假设用户在部署go-mysql-transfer之前的mysql已经开启了binlog模式。在服务启动时如果开启了全量同步stock。但是没有指定position，那么在执行增量同步时就会从binlog头开始同步，会导致许多没必要的同步信息处理。
- 是不是可以在开启了全量同步后，使用 `show master status` 查询一下当前mysql的binlog位置并在此进行增量同步呢？

**Comment by wj596** [comment]
有命令可以指定，最近在整理的新版文档中会详细写： ./go-mysql-transfer -config app.yml -position mysql-bin.000025 993779648


mysql-bin.000025 993779648这两个值是从，show master status 查询出来的

**Comment by a775189488** [comment]
> 有命令可以指定，最近在整理的新版文档中会详细写： ./go-mysql-transfer -config app.yml -position mysql-bin.000025 993779648
> 
> mysql-bin.000025 993779648这两个值是从，show master status 查询出来的

好的谢谢
