### ISSUE TITLE
redis多纬度需求以及过期时间设置需求~

### ISSUE THREAD

**Issue by 23233** [wj596/go-mysql-transfer#26]
### 需求背景
这样同步redis想必大家都是为了做cache层使用的吧

### 过期时间设置
当前关于同步到redis 在代码中是写死的过期时间为0 实际需求中可能需要按需写入 例如10秒 1天等情况 也需要更新时自动进行续期

### 多纬度
举例： 用户表中有 手机号 微信号 ID 一般业务中 是会把ID全量写入cache 其他纬度 例如手机号 作为一个key 映射到id的key 在redis下就为 user:1 value:一串json字符串  user:telephone:13888888888 value: user:1 user:weid:1234 value:user:1

**Comment by wj596** [comment]
你好：

1、“过期时间设置” 这个功能后续版本可以根据情况添加

2、“多纬度”这个没看太明白，你是指形成一个如“user:weid:1234”这样格式的KEY吗？

**Comment by 23233** [comment]
是的 key相当于是 {prefix}:{column}:{row_value} 指向 存储的完整信息的 user:1

没事 讨论一下 我已经fork自己改了 只是借楼看看大家是否都有这种小型同步cache的需求~

特别感谢大佬前期所做的工作！

**Comment by wj596** [comment]
ok,后面希望能把你改动的成果分享出来
