### ISSUE TITLE
不支持多张表一起吗？？

### ISSUE THREAD

**Issue by xieyuhua** [wj596/go-mysql-transfer#3]
不支持多张表一起吗？？

**Comment by wj596** [comment]
配置多个rule就行了

**Comment by xieyuhua** [comment]
有示例没有，我配置了一个，就是感觉被覆盖了，只执行了最后一个rule，



---原始邮件---
发件人: "wangjie"<notifications@github.com&gt;
发送时间: 2020年9月18日(周五) 晚上8:45
收件人: "wj596/go-mysql-transfer"<go-mysql-transfer@noreply.github.com&gt;;
抄送: "xieyuhua"<1130107545@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wj596/go-mysql-transfer] 不支持多张表一起吗？？ (#3)




 
配置多个rule就行了

**Comment by wj596** [comment]
#规则配置  
rule:
  -
    schema: eseap #数据库名称
    table: t_user #表名称
    column_underscore_to_camel: true #列名称下划线转驼峰,默认为false
    value_encoder: json  #
    redis_structure: string # 
  -
    schema: eseap #数据库名称
    table: t_sign #表名称
    column_underscore_to_camel: true #
    value_encoder: json  #
    redis_structure: string #
