### ISSUE TITLE
编译 go-mysql-transfer报错

### ISSUE THREAD

**Issue by angelyouyou** [wj596/go-mysql-transfer#44]
![image](https://user-images.githubusercontent.com/12936259/113387639-49bb9980-93bf-11eb-9dd2-1d2d7369018c.png)

**Comment by soldier-xq** [comment]
![image](https://user-images.githubusercontent.com/33277777/150983834-ef2f1b56-5cc9-4364-a798-5c003d06d601.png)
关掉就可以了，没有template模板文件
